### ISSUE TITLE
Running Analyze.decompose_fit using custom database not working

### ISSUE THREAD

**Issue by esavage111** [AlexandrovLab/SigProfilerAssignment#14] opened 2022-04-06 18:00 UTC
Code run:
```
from SigProfilerAssignment import Analyzer as Analyze
signatures="output_extractor_SBS/SBS96/Suggested_Solution/SBS96_De-Novo_Solution/Signatures/SBS96_De-Novo_Signatures.txt"
activities="output_extractor_SBS/SBS96/Suggested_Solution/SBS96_De-Novo_Solution/Activities/SBS96_De-Novo_Activities_refit.txt"
samples="output_extractor_SBS/SBS96/Samples.txt"
output="output_extractor_SBS_decompose_v2_newtool"
database_v2="COSMIC_v2_SBS_GRCh37.txt"
Analyze.decompose_fit(samples, output, signatures=signatures, signature_database=database_v2,genome_build="GRCh37",  make_decomposition_plots=True, collapse_to_SBS96=False, connected_sigs=False, verbose=False)
```

Output files contains decomposed solution using COSMIC 3.2 database instead of custom database (cosmic 2.0). Using old method from SigProfilerExtractor decomposes solution to custom database.

**Comment by rvangara** [comment] 2022-06-05 21:41
Apologies for the delay,

The issue is resolved in the new version of SPA 0.0.6.

Thanks!

**Closed by rvangara** 2022-06-05 21:41 UTC
Labels: Working on it
