### ISSUE TITLE
Unable to decompose de novo copy number signatures 

### ISSUE THREAD

**Issue by aliahhawari** [AlexandrovLab/SigProfilerAssignment#68] opened 2023-01-06 10:33 UTC
I am using SigProfilerAssignment v0.0.24 and have been unable to decompose my de novo CN signatures. I was able to decompose them using v0.0.18. I extracted these signatures using SigProfilerExtractor v1.1.19, signatures in the Suggested_Solution were decomposed. However, when running SigProfilerAssignment v0.0.24 and v0.0.21 to decompose the de novo signatures from the other solutions, an error returned. If I use SigProfilerAssignment v0.0.18, I could decompose and get the results, but only the CNV_Decomposition_plots.pdf is empty (other plots fine).

**Comment by marcos-diazg** [comment] 2023-01-06 11:55
Dear @aliahhawari,

Thanks for reaching out. Could you please let us know which error messages you are getting? Also, please check that you are using the latest version also for SigProfilerPlotting (v1.3.8).

**Comment by aliahhawari** [comment] 2023-01-06 12:47
Hi Marcos, 
A snippet of it is as below. I am using SigProfilerPlotting (v1.3.8). I am using SigProfilerExtractor v1.1.19, and was able to extract de novo signatures, and I can see the decomposed solution for the Suggested_Solution. But when using SigProfilerAssignment v0.0.24 to decompose the rest of the de novo signatures, I get this error: 
![image](https://user-images.githubusercontent.com/66627434/211014490-882dafb5-986e-4694-b3a5-85d6e1c137c1.png)

**Comment by marcos-diazg** [comment] 2023-01-06 12:54
Thanks for the quick reply. Could you please share the command you are using to run the tool, the JOB_METADATA file, as well as the input matrix of _de novo_ mutational signatures passed to the `signatures` parameter? Alternatively, happy to follow up by email (mdiazgay@health.ucsd.edu) if you prefer.

**Comment by marcos-diazg** [comment] 2023-02-01 05:55
Indeed, this problem was caused by an issue with the naming of the _de novo_ extracted CNV and SV mutational signatures by SigProfilerExtractor. This was fixed in the most recent v1.1.20 version. Thanks again @aliahhawari for reaching out.

**Closed by marcos-diazg** 2023-02-01 05:55 UTC
